# shellcheck shell=bash
# shellcheck disable=1090,1091
# vim: set ft=sh:
echo "$HOSTNAME $(date +"%Y-%m-%d %H:%M:%S") $$ $PPID bash/bash_profile" >> "$HOME/.dot_log"

# Initialise DOTFILES
[[ -f "$HOME/.dot" ]] && . "$HOME/.dot"

# NFS/Xauth fix
if [[ -n $SSH_CLIENT ]]
then
	export XAUTHORITY=$HOME/.Xauthority-$HOSTNAME
fi

# Load common profile
[[ -f $HOME/.profile ]] && . "$HOME/.profile"

umask 022

# Source the bashrc if required
ENV=~/.bashrc
tty -s
(( $? == 0 )) && source $ENV
