echo $(date +"%Y-%m-%d %H:%M:%S") $$ $PPID bash/bash_profile >> $HOME/.dot_log

# Initialise DOTFILES
[ -f $HOME/.dot ] && . $HOME/.dot

# NFS/Xauth fix
if [[ -n $SSH_CLIENT ]]
then
	export XAUTHORITY=$HOME/.Xauthority-$HOSTNAME
fi

# Load common profile
[ -f $HOME/.profile ] && . $HOME/.profile

# Update window title on prompt
PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD}\007"'

umask 022

# Source the bashrc if required
ENV=~/.bashrc
tty -s
(( $? == 0 )) && source $ENV
